version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:12.13.0-browsers

    working_directory: ~/app
    steps:
      - checkout

      - run:
          name: install node modules
          command: yarn install

      - run:
          name: clean
          command: yarn clean

      - run:
          name: build
          command: yarn build

      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;

      - run:
          name: deploy via SFTP
          command: lftp sftp://${username}:${password}@${hostname} -e "set sftp:auto-confirm yes ;mirror -v -R ./public ${target_location}; quit"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - prod
