export default [
  {
    slide: {
      tag: "Media Streaming",
      title: {
        "en-US": "Netflix’s Brazilian users VS US users",
        "zh-HK": "Netflix’s Brazilian users VS US users",
        "zh-CN": "Netflix’s Brazilian users VS US users",
      },
      description: {
        "en-US":
          "Netflix’s customer retention in Brazil over the past 36 months showed that users in Brazil are extremely loyal. Over 60% of Brazilian users still subscribe to the service 2 years after joining. For US users, even though the shorter-period retention curve looks very similar, the long-term retention rate is lower than that of the Brazilian ones.",
        "zh-HK":
          "Netflix’s customer retention in Brazil over the past 36 months showed that users in Brazil are extremely loyal. Over 60% of Brazilian users still subscribe to the service 2 years after joining. For US users, even though the shorter-period retention curve looks very similar, the long-term retention rate is lower than that of the Brazilian ones.",
        "zh-CN":
          "Netflix’s customer retention in Brazil over the past 36 months showed that users in Brazil are extremely loyal. Over 60% of Brazilian users still subscribe to the service 2 years after joining. For US users, even though the shorter-period retention curve looks very similar, the long-term retention rate is lower than that of the Brazilian ones.",
      },
    },
    chartOption: {
      title: {
        "en-US":
          "Customer Retention Rate - Months Since First Purchases until 2019",
        "zh-HK": "用戶複購率",
        "zh-CN": "用戶複購率",
      },
      legend: {
        "en-US": ["US", "Brazil"],
        "zh-HK": ["美國", "巴西"],
        "zh-CN": ["美國", "巴西"],
      },
      xAxis: {
        axisLabelInterval: 2,
        data: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
      yAxis: {
        // eslint-disable-next-line
        axisLabelFormatter: "{value}%",
      },
      series: [
        [
          "86.88",
          "80.00",
          "75.63",
          "73.75",
          "71.38",
          "69.13",
          "66.63",
          "64.25",
          "63.38",
          "62.50",
          "61.63",
          "61.00",
          "60.25",
          "59.62",
          "58.75",
          "58.38",
          "57.38",
          "57.00",
          "56.63",
          "56.13",
          "55.38",
          "55.25",
          "54.25",
          "53.50",
        ],
        [
          "89.09",
          "84.79",
          "81.57",
          "79.34",
          "77.50",
          "76.42",
          "75.73",
          "74.58",
          "73.35",
          "72.43",
          "71.35",
          "70.74",
          "69.89",
          "69.12",
          "68.20",
          "67.28",
          "66.82",
          "66.05",
          "65.36",
          "64.82",
          "64.36",
          "63.75",
          "63.29",
          "62.90",
        ],
      ],
    },
  },
  {
    slide: {
      tag: "GAMES",
      title: {
        "en-US": "Chinese Players’ red envelope money goes to Honor of Kings",
        "zh-HK": "Chinese Players’ red envelope money goes to Honor of Kings",
        "zh-CN": "Chinese Players’ red envelope money goes to Honor of Kings",
      },
      description: {
        "en-US":
          "Grossed over USD 2.55 Billion from In-App-Purchases.\nAverage paying user spends around USD $38.63\nUSD $6.68 per order.",
        "zh-HK":
          "新賽季發布史上最大更新，\n推出全新“戰令”功能，\n春節假期首周收入環比增長 250% 第一季度用戶平均消費翻倍",
        "zh-CN":
          "新赛季发布史上最大更新，\n推出全新“战令”功能，\n春节假期首周收入环比增长 250% 第一季度用户平均消费翻倍",
      },
    },
    chartOption: {
      title: {
        "en-US": "Average Paying User Spending",
        "zh-HK": "銷售變化趨勢",
        "zh-CN": "销售变化趋势",
      },
      legend: {
        "en-US": ["Honor of Kings"],
        "zh-HK": ["王者榮耀"],
        "zh-CN": ["王者荣耀"],
      },
      xAxis: {
        axisLabelInterval: 1,
        data: [
          "w1\n2019",
          "w2\n2019",
          "w3\n2019",
          "w4\n2019",
          "w5\n2019",
          "w6\n2019",
          "w7\n2019",
          "w8\n2019",
          "w9\n2019",
          "w10\n2019",
          "w11\n2019",
          "w12\n2019",
          "w13\n2019",
        ],
      },
      yAxis: {
        // eslint-disable-next-line
        axisLabelFormatter: "{value}",
      },
      series: [
        [
          166.48,
          130.22,
          213.24,
          157.96,
          201.8,
          501.55,
          241.6,
          140.36,
          82.65,
          75.43,
          54.75,
          46.62,
          87.57,
        ],
      ],
    },
  },
  {
    slide: {
      tag: "Apps",
      title: {
        "en-US": "MOMO beats estimates amid pressure from authority ",
        "zh-HK": "MOMO beats estimates amid pressure from authority ",
        "zh-CN": "MOMO beats estimates amid pressure from authority ",
      },
      description: {
        "en-US":
          "From April to July, MOMO's successful dating app Tantan(China’s Tinder) was removed from app stores in China. The app’s revenue was close to zero for over two months. However, on the first week it went live again, the number of paying users of Tantan soon went up by 50% compared to where it was 2 months ago.",
        "zh-HK":
          "From April to July, MOMO's successful dating app Tantan(China’s Tinder) was removed from app stores in China. The app’s revenue was close to zero for over two months. However, on the first week it went live again, the number of paying users of Tantan soon went up by 50% compared to where it was 2 months ago.",
        "zh-CN":
          "From April to July, MOMO's successful dating app Tantan(China’s Tinder) was removed from app stores in China. The app’s revenue was close to zero for over two months. However, on the first week it went live again, the number of paying users of Tantan soon went up by 50% compared to where it was 2 months ago.",
      },
    },
    chartOption: {
      title: {
        "en-US": "Paying Users Trend Index",
        "zh-HK": "用戶變化趨勢指數",
        "zh-CN": "用户变化趋势指数",
      },
      legend: {
        "en-US": ["Tantan - Genuine Dating"],
        "zh-HK": ["Tantan - Genuine Dating"],
        "zh-CN": ["Tantan - Genuine Dating"],
      },
      xAxis: {
        axisLabelInterval: 1,
        data: [
          "w1\n2019",
          "w2\n2019",
          "w3\n2019",
          "w4\n2019",
          "w5\n2019",
          "w6\n2019",
          "w7\n2019",
          "w8\n2019",
          "w9\n2019",
          "w10\n2019",
          "w11\n2019",
          "w12\n2019",
          "w13\n2019",
          "w14\n2019",
          "w15\n2019",
          "w16\n2019",
          "w17\n2019",
          "w18\n2019",
          "w19\n2019",
          "w20\n2019",
          "w21\n2019",
          "w22\n2019",
          "w23\n2019",
          "w24\n2019",
          "w25\n2019",
          "w26\n2019",
          "w27\n2019",
          "w28\n2019",
          "w29\n2019",
        ],
      },
      yAxis: {
        // eslint-disable-next-line
        axisLabelFormatter: "{value}",
      },
      series: [
        [
          1.39,
          1.72,
          1.95,
          1.71,
          1.63,
          1.93,
          2.03,
          2.09,
          2.24,
          1.96,
          1.63,
          1.98,
          1.48,
          1.64,
          1.87,
          1.74,
          1.52,
          0.74,
          0.05,
          0.05,
          0.06,
          0.03,
          0.04,
          0.04,
          0.05,
          0.04,
          0.08,
          0.63,
          2.88,
        ],
      ],
    },
  },
]
